-- Migration for AI-Generated Workout Calendar Integration
-- This adds support for AI-generated training plans in the calendar

-- Add columns to athlete_calendar for AI workouts
ALTER TABLE athlete_calendar ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT FALSE;
ALTER TABLE athlete_calendar ADD COLUMN IF NOT EXISTS target_hr_min INTEGER;
ALTER TABLE athlete_calendar ADD COLUMN IF NOT EXISTS target_hr_max INTEGER;
ALTER TABLE athlete_calendar ADD COLUMN IF NOT EXISTS intensity VARCHAR(20);
ALTER TABLE athlete_calendar ADD COLUMN IF NOT EXISTS week_number INTEGER;
ALTER TABLE athlete_calendar ADD COLUMN IF NOT EXISTS workout_type TEXT;
ALTER TABLE athlete_calendar ADD COLUMN IF NOT EXISTS distance_km NUMERIC;
ALTER TABLE athlete_calendar ADD COLUMN IF NOT EXISTS duration_minutes INTEGER;
ALTER TABLE athlete_calendar ADD COLUMN IF NOT EXISTS description TEXT;

-- Create AI training plans table
CREATE TABLE IF NOT EXISTS ai_training_plans (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    goal_type VARCHAR(50) NOT NULL,
    fitness_level VARCHAR(20) NOT NULL,
    weeks_to_goal INTEGER NOT NULL,
    training_days_per_week INTEGER NOT NULL,
    target_race_date TIMESTAMP WITH TIME ZONE,
    total_workouts INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status VARCHAR(20) DEFAULT 'active', -- active, completed, cancelled
    CONSTRAINT valid_goal_type CHECK (goal_type IN ('marathon', 'half_marathon', '10k', '5k', 'fitness', 'weight_loss')),
    CONSTRAINT valid_fitness_level CHECK (fitness_level IN ('beginner', 'intermediate', 'advanced')),
    CONSTRAINT valid_training_days CHECK (training_days_per_week >= 3 AND training_days_per_week <= 7)
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_ai_training_plans_user_id ON ai_training_plans(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_training_plans_status ON ai_training_plans(status);
CREATE INDEX IF NOT EXISTS idx_athlete_calendar_ai_generated ON athlete_calendar(athlete_id, is_ai_generated) WHERE is_ai_generated = TRUE;

-- Enable RLS on ai_training_plans
ALTER TABLE ai_training_plans ENABLE ROW LEVEL SECURITY;

-- RLS policies for ai_training_plans
CREATE POLICY "Users can view their own training plans"
    ON ai_training_plans FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own training plans"
    ON ai_training_plans FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own training plans"
    ON ai_training_plans FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own training plans"
    ON ai_training_plans FOR DELETE
    USING (auth.uid() = user_id);

-- Create a view for workout statistics
CREATE OR REPLACE VIEW ai_workout_stats AS
SELECT 
    athlete_id,
    COUNT(*) as total_ai_workouts,
    COUNT(CASE WHEN scheduled_date = CURRENT_DATE THEN 1 END) as today_workouts,
    COUNT(CASE WHEN scheduled_date = CURRENT_DATE + 1 THEN 1 END) as tomorrow_workouts,
    COUNT(CASE WHEN scheduled_date >= CURRENT_DATE AND scheduled_date < CURRENT_DATE + 7 THEN 1 END) as this_week_workouts
FROM athlete_calendar
WHERE is_ai_generated = TRUE
GROUP BY athlete_id;

-- Grant access to the view
GRANT SELECT ON ai_workout_stats TO authenticated;

COMMENT ON TABLE ai_training_plans IS 'Stores AI-generated training plans for athletes';
COMMENT ON COLUMN athlete_calendar.is_ai_generated IS 'Indicates if workout was generated by AI';
COMMENT ON COLUMN athlete_calendar.target_hr_min IS 'Minimum target heart rate for workout';
COMMENT ON COLUMN athlete_calendar.target_hr_max IS 'Maximum target heart rate for workout';
COMMENT ON COLUMN athlete_calendar.intensity IS 'Workout intensity level: low, moderate, high';
COMMENT ON COLUMN athlete_calendar.week_number IS 'Week number in the training plan';
